from django.conf import settings
from django.db import models


class Employee(models.Model):
    employee_code = models.CharField(max_length=32, unique=True)
    user = models.OneToOneField(settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.SET_NULL)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    department = models.CharField(max_length=120, blank=True)
    designation = models.CharField(max_length=120, blank=True)
    date_of_joining = models.DateField(null=True, blank=True)
    status = models.CharField(max_length=20, default="ACTIVE")
    created_at = models.DateTimeField(auto_now_add=True)
    is_vendor_staff = models.BooleanField(default=False)
    hourly_rate = models.DecimalField(max_digits=12, decimal_places=2, default=0)

    # Payroll profile fields used by the payroll upload, salary slip, and dashboard.
    month = models.CharField(max_length=32, default="June 2026", blank=True)
    work_location = models.CharField(max_length=120, blank=True)
    account_number = models.CharField(max_length=64, blank=True)
    ifsc_code = models.CharField(max_length=32, blank=True)
    bank_name = models.CharField(max_length=120, blank=True)
    payment_status = models.CharField(max_length=20, default="Unpaid", blank=True)
    utr = models.CharField(max_length=64, blank=True)
    base_salary = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    working_days = models.DecimalField(max_digits=6, decimal_places=2, default=0)
    basic_pay = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    hra = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    other_allowance = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    stat_bonus = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    attendance_bonus = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    leave_encashment = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    performance_incentive = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    extra_payment = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    shipment_incentive = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    mobile_allowance = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    meal_incentive = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    group_incentive = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    night_allowance = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    national_holiday_pay = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    retention_bonus = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    arrear_payment = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    esi = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    pf = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    lwf = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    meal_debit = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    refyne_debit = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    advance_salary = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    pt = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    e_bike_debit = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    advance_payments_in_weeks = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    shipment_debit = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    accommodation_recovery = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    notice_period_deduction = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    cod_loss = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    tshirt_recovery = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    ewf_deduction = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    tds = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    candidate_payout = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    service_charge = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    gst_amount = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    net_pay = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    total_payment = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    invoice_number = models.CharField(max_length=64, blank=True)
    invoice_topic = models.CharField(max_length=255, blank=True)
    invoice_status = models.CharField(max_length=32, blank=True)
    invoice_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return f"{self.employee_code} - {self.first_name} {self.last_name}"
