# Generated by Django 5.2.6 on 2026-06-11 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyprofile',
            options={'verbose_name': 'Company Profile'},
        ),
    ]
