# Generated by Django 5.2.15 on 2026-06-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_companyprofile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='account_name',
            field=models.CharField(default='QT Consultancy Private Limited', max_length=255),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='account_no',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='bank_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='branch_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='ifsc_code',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='logo_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='seal_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='signatory_name',
            field=models.CharField(default='QT Consultancy', max_length=255),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='signature_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
