# Generated by Django 5.2.6 on 2026-06-10 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(blank=True, max_length=32)),
                ('invoice_number', models.CharField(max_length=64, unique=True)),
                ('invoice_date', models.DateField()),
                ('topic', models.CharField(blank=True, max_length=255)),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('client_address', models.TextField(blank=True)),
                ('client_gstin', models.CharField(blank=True, max_length=32)),
                ('client_state', models.CharField(blank=True, max_length=64)),
                ('client_state_code', models.CharField(blank=True, max_length=16)),
                ('supply_state', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(default='UNPAID', max_length=32)),
                ('gross_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('final_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
