# Generated by Django 5.2.15 on 2026-06-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='account_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='account_no',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='invoice',
            name='balance_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='branch_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='destination_company',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='final_invoice_amt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='gstin_a',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ifsc_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='invoice',
            name='location',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='invoice',
            name='reverse_charge',
            field=models.CharField(blank=True, default='No', max_length=32),
        ),
        migrations.AddField(
            model_name='invoice',
            name='source_company',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='state',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='invoice',
            name='state_code',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='invoice',
            name='state_code_a',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='invoice',
            name='taxable_amt_before_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_tax_amt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='website',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
