# Generated by Django 5.2.6 on 2026-06-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_accommodation_recovery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_vendor_staff',
            field=models.BooleanField(default=False),
        ),
    ]
