# Generated by Django 5.2.6 on 2026-06-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_hourly_rate_employee_is_vendor_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
